### ISSUE TITLE
No license and copyright information in the files

### ISSUE THREAD

**Issue by OliverFendt** [heremaps/oss-review-toolkit#1]
Since this is an open Source compliance toolkit, I would love to see the best practises for a good OSS project realized in this project. 
Some of the best practises are:
1. Put a copyrihgt notice in each file
2. Put the relevant Strandard License Header in file (or a statement like This file is licensed under --SPDX Short Identifier --

The FSFE hast set up a Project with best practizes relevant for smart license compliance support, the proejct is called reuse. Please see https://reuse.software/
No file of the current release carries a standarde license haeder, there is no license information in the files at all. The same applies to the copyright information, except the README.md file.

Regarding the README.md file, please remove the statement "See the [LICENSE](./LICENSE) file in the root of this project for license details." because no license scanner can "auto conclude" such a statement.

The file oss-review-toolkit-preview/analyzer/src/funTest/assets/projects/synthetic/mixed/NPMNestedMaven/package.json
{
"name": "npmnestedmaven",
"version": "1.0.0",
"description": "A dummy NPM project with a nested Maven project",
"scripts": {
"test": "echo \"Error: no test specified\" && exit 1"
},
"author": "Sebastian Schuberth",
"license": "ISC",
"repository": {
"type": "git",
"url": "https://github.com/heremaps/oss-review-toolkit.git"
}
}
Carries a license information which doea not fit. Even in case of test files you should care for license hygiene

**Comment by sschuberth** [comment]
Thanks for pointing out https://reuse.software/! We'll certainly follow best practices regarding copyright / license headers and test data once we publish the final history.

I believe we should keep the reference from `README.md` to `LICENSE`. This is a hint for humans only, as GitHub only shows the contents of `README.md` on the front page, but inlining `LICENSE` into `README.md` does not really make sense.

**Comment by sschuberth** [comment]
We just pushed the final history to the `master` branch which has the copyright / license headers added.
