### ISSUE TITLE
Add declared_licenses_processed to Analyzer

### ISSUE THREAD

**Issue by tsteenbe** [heremaps/oss-review-toolkit#1131]
Besides the declared license findings I propose we add declared_licenses_processed similar to vcs_processed to translate an "Apache License, Version 2.0" finding to SPDX identifier Apache-2.0.
Proposing this as it would save ORT users to do the translation to SPDX identifiers itself whilst we have this functionality already in ORT. Would also make it possible in the WebApp report to de-duplicate multiple occurrences of the same license in the license tables/pie charts

**Comment by sschuberth** [comment]
Implementing this would also solve https://github.com/heremaps/oss-review-toolkit/issues/908.

**Comment by sschuberth** [comment]
Will be done as part of https://github.com/heremaps/oss-review-toolkit/pull/1293.

**Comment by sschuberth** [comment]
@neubs-bsi, this was something you also were interested it, and it has been implemented now.
