### ISSUE TITLE
Missing redirect/DNS config on http://oss-review-toolkit.org/

### ISSUE THREAD

**Issue by pombredanne** [heremaps/oss-review-toolkit#1298]
http://oss-review-toolkit.org/ does not go anywhere while http://www.oss-review-toolkit.org/ redirects to https://github.com/heremaps/oss-review-toolkit

As a result https://github.com/nexB/scancode-toolkit/pull/1372 and the main page for this repo are going to dead links for now.
/cc @sschuberth

**Comment by sschuberth** [comment]
Odd, it works in the browser for me, but the browser probably as an automatic fall-back to adding "www." at the start. But I can confirm the issue:

```
C:\Users\sebastian>ping oss-review-toolkit.org
Ping request could not find host oss-review-toolkit.org. Please check the name and try again.

C:\Users\sebastian>ping www.oss-review-toolkit.org

Pinging www.oss-review-toolkit.org [192.64.119.220] with 32 bytes of data:
Reply from 192.64.119.220: bytes=32 time=189ms TTL=44
```

@tsteenbe, can you please fix this?

**Comment by pombredanne** [comment]
@sschuberth re 
> Odd, it works in the browser for me,

I am using Firefox FWIW

**Comment by sschuberth** [comment]
Me too.

**Comment by lenucksi** [comment]
Good ol' ```dig``` confirms the lack of an ```A/AAAA``` or ```CNAME``` entry too - at least as of now. Also, when adding that subdomain to the one domain checking the others for the same issue might be a good idea.

**Comment by tsteenbe** [comment]
Mad some changes to our DNS settings for all our domains - oss-review-toolkit.com oss-review-toolkit.org, ossreviewtoolkit.com, ossreviewtoolkit.org and reviewtoolkit.org  

I will give it a couple of hours for the DNS changes to propagate and then retest.

**Comment by pombredanne** [comment]
@tsteenbe It works! thanks. Closing.
