### ISSUE TITLE
Upgrade to ScanCode 3.x

### ISSUE THREAD

**Issue by sschuberth** [heremaps/oss-review-toolkit#1381]
@pombredanne, any hints about what would be a good 3.x version to switch to? Is 3.0.2 already expected to be reasonably stable, or should we wait for another imminent patch release?

**Comment by pombredanne** [comment]
In general and here in particular tags are as stable as it gets. So you can go with 3.0.2 alright. There will be more releases pretty soon anyway. But that's always the case, so it is likely best to jump on the 3.x bandwagon sooner than later
