### ISSUE TITLE
`~` is not properly translated in relative file path for analyzer

### ISSUE THREAD

**Issue by tarkatronic** [heremaps/oss-review-toolkit#1384]
When I use a `~` for my project source code path, for example:

```
./gradlew cli:run --args="analyze -i ~/Documents/workspace/django-snow -o ~/Documents/workspace/ort_django_snow"
```

I get an error that the directory does not exist:

```
Scanning project path:
        /Users/jwilhelm/Documents/workspace/oss-review-toolkit/cli/~/Documents/workspace/django-snow
Exception in thread "main" java.lang.IllegalArgumentException: The provided path is not a directory: /Users/jwilhelm/Documents/workspace/oss-review-toolkit/cli/~/Documents/workspace/django-snow
```

Similarly, with the output path, a literal `~` folder was created to store the result.

I would have expected this to be translated to my `$HOME`.

**Comment by sschuberth** [comment]
That actually works as designed. Expanding `~` to the current user's home path is a feature of the shell you are using, and in that regard this is also a platform-specific feature, whereas ORT is a cross-platform tool. On Windows, for example, you don't have this feature at all.

The `--args` string is directly passed to ORT without going through the shell first, like it would be if you were running

    $ ./gradlew installDist
    $ ./cli/build/install/ort/bin/ort analyze -i ~/Documents/workspace/django-snow -o ~/Documents/workspace/ort_django_snow

Using the latter also the work-around I'd suggest if you want to be using `~`. The same applies for using `$HOME`, BTW, as environment variable expansion also is a feature of your shell: The program being running never actually sees this variable name.

Does that make sense to you?

**Comment by tarkatronic** [comment]
Interesting; that does make sense. I think this comes from my own
unfamiliarity with Kotlin. I'm used to being able to resolve these, in a
cross-platform manner, in Python with [os.path.expanduser](
https://docs.python.org/3/library/os.path.html#os.path.expanduser). But
from your response, it sounds like Kotlin does not have an equivalent?

**Comment by sschuberth** [comment]
As we're targeting the JVM with Kotlin, it's not (only) a Kotlin-thing, but (also) a Java-thing, and indeed neither Java nor Kotlin have such a helper method like Python built-in, see e.g. [this question](https://stackoverflow.com/q/6803913/1127485).

However, I'm not totally opposed to doing that, if it makes you life significantly easier. It's just that e.g. Windows users would probably *not* expect such an expansion to happen, but that should only matter if they actually tried to use a directory with a literal "~" as its name, which is rather unlikely. Or we make the expansion only happen on non-Windows in general.
