### ISSUE TITLE
Progress indicator of how many dependencies remain to scan

### ISSUE THREAD

**Issue by tarkatronic** [heremaps/oss-review-toolkit#1385]
I'm currently scanning a JavaScript project, and the scan job has been running in excess of 3 hours. While I expect this, given the hell that is `node_modules`, I would love to see an indicator of how many of the dependencies have been scanned, vs how many remain.

I wouldn't expect any kind of timer/countdown; simply just a straight package count.

**Comment by sschuberth** [comment]
We actually already have that, see [this code](https://github.com/heremaps/oss-review-toolkit/blob/master/scanner/src/main/kotlin/LocalScanner.kt#L159). You just need to raise the default log level of `WARN` to `INFO` by passing `--info` to the CLI module. Let me know if this works for you.

**Comment by NicolasToussaint** [comment]
Nice!

In the meantime, I am cheating with the `grep`command:
`<ort-cmd>  | tee $LOG_FILE | grep 'INFO  - Starting scan'`

Which outputs: 
```
12:05:20.489 INFO  - Starting scan of 'NPM::abab:2.0.0' (1/1004).
12:05:46.234 INFO  - Starting scan of 'NPM::abbrev:1.1.1' (2/1004).
12:06:06.510 INFO  - Starting scan of 'NPM::acorn-dynamic-import:4.0.0' (3/1004).
12:06:31.993 INFO  - Starting scan of 'NPM::acorn-globals:4.3.0' (4/1004).
12:06:51.869 INFO  - Starting scan of 'NPM::acorn-walk:6.1.1' (5/1004).
12:12:20.650 INFO  - Starting scan of 'NPM::acorn:5.7.3' (6/1004).
12:18:00.900 INFO  - Starting scan of 'NPM::acorn:6.1.0' (7/1004).
```

**Comment by sschuberth** [comment]
Closing this, assuming the current implementation to be sufficient. Please reopen otherwise.
