### ISSUE TITLE
Support `Go module` as Suported Package Manager

### ISSUE THREAD

**Issue by silenceleaf** [heremaps/oss-review-toolkit#1400]
From go 1.11 it has "go mod ..."(go module) command as official build tool. Does OSS tools has plan to support this package management method?

This is an official feature, means no third party dependency management needed at all. Hope we can support this official building tool in OSS.

Thanks!

**Comment by sschuberth** [comment]
Some background information is at https://github.com/golang/go/wiki/Modules#daily-workflow, in particular `go list -m all`.

@silenceleaf, would you know about a small Open Source project that uses go modules which we could use as a test case?

**Comment by silenceleaf** [comment]
no, I don't. you might want to create a small project just for testing.

**Comment by sschuberth** [comment]
Note to myself: Maybe check if https://github.com/ribice/glice could be leveraged.

**Comment by tsteenbe** [comment]
We can simply use `go mod vendor && go list -json -m -mod=vendor all`

// Force download to vendor folder
go mod vendor

// List all dependencies in vendor
go list -json -m -mod=vendor all

For debugging 
```
go mod vendor && go list -json -m -mod=vendor all | jq --slurp --raw-output '[.[] | select((.Main?) | not) | {name: .Path, version: .Version, location: .Dir}] | @json'
```

**Comment by tsteenbe** [comment]
PR implementing GoMod support see https://github.com/heremaps/oss-review-toolkit/pull/1937

**Comment by silenceleaf** [comment]
Thanks guys!

**Comment by fviernau** [comment]
Filed #2033 as a potential extension / improvement of the current implementation, it has some of my research results.
