### ISSUE TITLE
./gradlew cli:dockerBuildImage  failed on Arch Linux

### ISSUE THREAD

**Issue by silenceleaf** [heremaps/oss-review-toolkit#1418]
I was trying remove all related docker image and build, but still fail

=================================
junyan@arch ~/W/oss-review-toolkit> sudo ./gradlew cli:dockerBuildImage
Configuration on demand is an incubating feature.
> Task :model:generateVersionResource UP-TO-DATE
> Task :model:processResources UP-TO-DATE
> Task :utils:processResources UP-TO-DATE
> Task :downloader:processResources UP-TO-DATE
> Task :evaluator:processResources UP-TO-DATE
> Task :spdx-utils:generateGrammarSource UP-TO-DATE
> Task :analyzer:processResources UP-TO-DATE
> Task :reporter:processResources UP-TO-DATE
Step 1/4 : FROM openjdk:11-jre-slim-sid

---> 9e26cc9de624
Step 2/4 : ENV     BOWER_VERSION=1.8.8     BUNDLER_VERSION=1.17.3-3     COMPOSER_VERSION=1.8.4-1     GO_DEP_VERSION=0.5.0-1+B10     HASKELL_STACK_VERSION=1.7.1-3     NPM_VERSION=5.8.0+DS6-4     PYTHON_PIP_VERSION=18.1-4     PYTHON_VIRTUALENV_VERSION=15.1.0     SBT_VERSION=0.13.13-2     YARN_VERSION=1.13.0     SCANCODE_VERSION=2.9.7

> Task :scanner:processResources UP-TO-DATE
> Task :reporter-web-app:yarnInstall UP-TO-DATE
---> Running in 084ba55d90f1
Removing intermediate container 084ba55d90f1
---> b981f54cfeb5
Step 3/4 : RUN apt-get update &&     apt-get install -y --no-install-recommends         curl         cvs         git         mercurial         subversion         bundler=$BUNDLER_VERSION         composer=$COMPOSER_VERSION         go-dep=$GO_DEP_VERSION         haskell-stack=$HASKELL_STACK_VERSION         npm=$NPM_VERSION         python-pip=$PYTHON_PIP_VERSION         sbt=$SBT_VERSION     &&     rm -rf /var/lib/apt/lists/*

---> Running in 707f2c12c86e

> Task :cli:dockerBuildBaseImage FAILED
Building image using context '/home/junyan/Work/oss-review-toolkit/cli/docker'.
Using tags 'ort-base:latest' for image.

> Task :reporter-web-app:yarnBuild
yarn run v1.15.2
$ node scripts/build.js
Creating an optimized production build...

> Task :spdx-utils:compileKotlin

> Task :reporter-web-app:yarnBuild
Removing unneeded files in build dir...
Creating ORT template file...
Compiled successfully.

File sizes after gzip:

  445.29 KB  build/static/js/2.0ed575ee.chunk.js
  51.63 KB   build/static/css/2.005b7502.chunk.css
  22.53 KB   build/static/js/main.df31dda5.chunk.js
  3.46 KB    build/static/css/main.3bd39d85.chunk.css
  763 B      build/static/js/runtime~main.9eb600ee.js

The project was built assuming it is hosted at ./.
You can control this with the homepage field in your package.json.

The build folder is ready to be deployed.

Find out more about deployment here:

  http://bit.ly/CRA-deploy

Done in 47.91s.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':cli:dockerBuildBaseImage'.
> Could not build image: failed to create endpoint zealous_curran on network bridge: failed to add the host (veth0420f4b) <=> sandbox (veth5f0e9ff) pair interfaces: operation not supported

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.3.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 50s
13 actionable tasks: 3 executed, 10 up-to-date

**Comment by sschuberth** [comment]
Some quick Internet search suggests this is [an issue specific to Arch Linux](https://github.com/moby/moby/issues/15341#issuecomment-218930712) and Docker, and not related to ORT.

**Comment by silenceleaf** [comment]
Yes, restart solve the previous problem

but I got a new one:  Version '18.1-4' for 'python-pip' was not found

I am sure I have python-pip installed in local, but this error is from docker building image.

==================================
sudo ./gradlew cli:dockerBuildImage
Configuration on demand is an incubating feature.
> Task :model:generateVersionResource UP-TO-DATE
> Task :model:processResources UP-TO-DATE
> Task :downloader:processResources UP-TO-DATE
> Task :utils:processResources UP-TO-DATE
> Task :evaluator:processResources UP-TO-DATE
> Task :analyzer:processResources UP-TO-DATE
> Task :reporter:processResources UP-TO-DATE
Step 1/4 : FROM openjdk:11-jre-slim-sid

---> 9e26cc9de624
Step 2/4 : ENV     BOWER_VERSION=1.8.8     BUNDLER_VERSION=1.17.3-3     COMPOSER_VERSION=1.8.4-1     GO_DEP_VERSION=0.5.0-1+B10     HASKELL_STACK_VERSION=1.7.1-3     NPM_VERSION=5.8.0+DS6-4     PYTHON_PIP_VERSION=18.1-4     PYTHON_VIRTUALENV_VERSION=15.1.0     SBT_VERSION=0.13.13-2     YARN_VERSION=1.13.0     SCANCODE_VERSION=2.9.7

---> Using cache
---> b981f54cfeb5
Step 3/4 : RUN apt-get update &&     apt-get install -y --no-install-recommends         curl         cvs         git         mercurial         subversion         bundler=$BUNDLER_VERSION         composer=$COMPOSER_VERSION         go-dep=$GO_DEP_VERSION         haskell-stack=$HASKELL_STACK_VERSION         npm=$NPM_VERSION         python-pip=$PYTHON_PIP_VERSION         sbt=$SBT_VERSION     &&     rm -rf /var/lib/apt/lists/*

---> Running in f1bf4674998a
> Task :scanner:processResources UP-TO-DATE
> Task :spdx-utils:generateGrammarSource UP-TO-DATE
> Task :spdx-utils:compileKotlin UP-TO-DATE
> Task :spdx-utils:compileJava UP-TO-DATE
> Task :reporter-web-app:yarnInstall UP-TO-DATE
> Task :spdx-utils:processResources UP-TO-DATE
> Task :spdx-utils:classes UP-TO-DATE
> Task :spdx-utils:inspectClassesForKotlinIC UP-TO-DATE
> Task :spdx-utils:jar UP-TO-DATE
> Task :utils:compileKotlin UP-TO-DATE
> Task :utils:compileJava NO-SOURCE
> Task :utils:classes UP-TO-DATE
> Task :utils:inspectClassesForKotlinIC
> Task :utils:jar
> Task :reporter-web-app:yarnBuild UP-TO-DATE
> Task :reporter:copyWebAppTemplate UP-TO-DATE
Get:1 http://cdn-fastly.deb.debian.org/debian sid InRelease [242 kB]
Get:2 http://cdn-fastly.deb.debian.org/debian sid/main amd64 Packages [8272 kB]

> Task :cli:dockerBuildBaseImage
Building image using context '/home/junyan/Work/oss-review-toolkit/cli/docker'.
Using tags 'ort-base:latest' for image.

Fetched 8514 kB in 6s (1507 kB/s)
Reading package lists...

Reading package lists...

Building dependency tree...
Reading state information...

[91mE: Version '18.1-4' for 'python-pip' was not found


> Task :cli:dockerBuildBaseImage FAILED
> Task :model:compileKotlin

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':cli:dockerBuildBaseImage'.
> Could not build image: The command '/bin/sh -c apt-get update &&     apt-get install -y --no-install-recommends         curl         cvs         git         mercurial         subversion         bundler=$BUNDLER_VERSION         composer=$COMPOSER_VERSION         go-dep=$GO_DEP_VERSION         haskell-stack=$HASKELL_STACK_VERSION         npm=$NPM_VERSION         python-pip=$PYTHON_PIP_VERSION         sbt=$SBT_VERSION     &&     rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.3.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 13s
22 actionable tasks: 4 executed, 18 up-to-date

**Comment by sschuberth** [comment]
> Version '18.1-4' for 'python-pip' was not found

Thanks for the information, PR https://github.com/heremaps/oss-review-toolkit/pull/1421 should fix that.

**Comment by sschuberth** [comment]
This should be fixed in *master* now.
