### ISSUE TITLE
StackOverflowError when analysing a php project

### ISSUE THREAD

**Issue by NicolasToussaint** [heremaps/oss-review-toolkit#1543]
When performing an Analysis on a PHP project, ORT crashes with a StackOverflowError.

I reproduce everytime, with yesterday's source code from Master.

The command I ran:
```
./gradlew -Djava.io.tmpdir=/data/tmp cli:run --args=--debug analyze --allow-dynamic-versions  --input-dir /sources/   --output-formats json   --output-dir /output
```
Extract from the logs:
```
15:57:47.871 DEBUG - (Above output is limited to each 20 heading and tailing lines.)
15:57:47.871 INFO  - Reading composer.lock file in /__project_path__/api/vendor/silex/silex...
Exception in thread "main" java.lang.StackOverflowError
	at java.util.HashMap.hash(HashMap.java:339)
	at java.util.HashMap.containsKey(HashMap.java:596)
	at java.util.HashSet.contains(HashSet.java:204)
	at com.here.ort.analyzer.managers.PhpComposer.buildDependencyTree(PhpComposer.kt:179)
	at com.here.ort.analyzer.managers.PhpComposer.buildDependencyTree(PhpComposer.kt:185)
```
More logs here: [ort-stackoverflow.log](https://github.com/heremaps/oss-review-toolkit/files/3265039/ort-stackoverflow.log)

I can produce more logs as needed, just ask :)

**Comment by sschuberth** [comment]
@NicolasToussaint, can you please check whether https://github.com/heremaps/oss-review-toolkit/pull/1544 fixes the issue for you, and can you share the OSS package that introduces the cyclic dependency, if so?

**Comment by NicolasToussaint** [comment]
@sschuberth the branch does fix the issue
But I'm not sure what info you need, is that the latest PHP component that was scanned ?
Looks like it's this:
-  ̀Reading composer.lock file in /__project_path__/api/vendor/silex/silex`
- http://silex.sensiolabs.org/

**Comment by sschuberth** [comment]
Great, thanks!
