### ISSUE TITLE
Capture the VCS revision actually fetched

### ISSUE THREAD

**Issue by jeffmcaffer** [heremaps/oss-review-toolkit#158]
In the Git downloader there is some code to refine the vcs revision that is fetched (e.g., looking up the package version as a tag). That gets the right source but the revision fetched is never recorded in the package data as far as I can tell. This info is key to get out and recorded somewhere.

**Comment by sschuberth** [comment]
Done as part of https://github.com/heremaps/oss-review-toolkit/pull/460.
