### ISSUE TITLE
Proxy setup is not pass along to all services and docker

### ISSUE THREAD

**Issue by heliocastro** [heremaps/oss-review-toolkit#1617]
On current Docker construction with proxied networks, several configurations need to be triggered on host machine to allow system move along.

For host part, this configuration as usual need be user done, i.e. .gradle/gradle.properties, or HTTPS_PROXY env variables.

The issue is that this configurations aren' t reflected to the docker container after initialisation, breaking gradle and regular downloads from inside container.

Solution requires at least mounting the proper .user related directories and expose the configured env variables to allow constructs continue properly.  

Reference: docker/build.sh

**Comment by sschuberth** [comment]
I'm uncertain why this would happen. We execute the build inside the Docker container as the current host user, see

https://github.com/heremaps/oss-review-toolkit/blob/020cc6e543c31dc94a12f49d5a04237fd3a7a0c3/docker/lib#L31

and as part of that we also mount $HOME to inside the Docker container, so config files like `~/.gradle/gradle.properties` should be present and be taken into account.

**Comment by sschuberth** [comment]
> The issue is that this configurations aren' t reflected to the docker container after initialisation, breaking gradle and regular downloads from inside container.

Could you please copy & paste the exact error message(s)?

**Comment by heliocastro** [comment]
Sorry for late answer. This is exactly what happens, with proper https and http proxy working

```
LMUCM780772:oss-review-toolkit helio$ docker/build.sh 
Sending build context to Docker daemon   2.56kB
Step 1/2 : FROM openjdk:8-jdk-alpine3.9
 ---> a3562aa0b991
Step 2/2 : RUN apk add --no-cache yarn
 ---> Using cache
 ---> 550499846c2a
Successfully built 550499846c2a
Successfully tagged ort-build:latest
No Gradle daemons are running.
Downloading https://services.gradle.org/distributions/gradle-5.5-all.zip

Exception in thread "main" java.net.UnknownHostException: services.gradle.org
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:666)
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
	at org.gradle.wrapper.Download.downloadInternal(Download.java:67)
	at org.gradle.wrapper.Download.download(Download.java:52)
	at org.gradle.wrapper.Install$1.call(Install.java:62)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)
```

To me seen like GradleWrapper is not respecting the proxy settings  for user/password
This case maybe ? https://issues.gradle.org/browse/GRADLE-1556
Although, it's state as fixed.

I will try override option on gradlew to double check

**Comment by heliocastro** [comment]
Confirmed.
As long we pass explicit -Dhttp.proxyUser, etc.. works.
Is basically the problem of ignoring user + password auth

**Comment by heliocastro** [comment]
As i already expected, more things related to same case would appear, here's second one:
`> Task :reporter-web-app:yarnInstall
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info If you think this is a bug, please open a bug report with the information provided in "/home/ort/reporter-web-app/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "https://registry.yarnpkg.com/recharts/-/recharts-1.6.2.tgz: tunneling socket could not be established, statusCode=407".

> Task :reporter-web-app:yarnInstall FAILED
> Task :spdx-utils:compileJava

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':reporter-web-app:yarnInstall'.
> Process 'command 'yarn'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.


* Get more help at https://help.gradle.org
Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.5/userguide/command_line_interface.html#sec:command_line_warnings
15 actionable tasks: 15 executed

BUILD FAILED in 5m 45s`

**Comment by kallesoranko** [comment]
Hi, I am having similar issues in an environment behind a proxy. Your second issue (with `:reporter-web-app:yarnInstall`)  can be solved by setting the proxy for yarn separately, like:
```
yarn config set proxy http://<proxy-host>:<proxy-port>
yarn config set https-proxy http://<proxy-host>:<proxy-port>
```

**Comment by sschuberth** [comment]
> To me seen like GradleWrapper is not respecting the proxy settings for user/password
> This case maybe ? https://issues.gradle.org/browse/GRADLE-1556

@heliocastro, the Gradle wrapper *does* respect proxy settings if they are configured as Java system properties. The Gradle wrapper does *not*, however, respect the `http_proxy` or `https_proxy` (Unix) environment variables, also see the stale PR at https://github.com/gradle/gradle/pull/89 that was never merged.

That said, if you have configured a proxy for Gradle on the host as documented [here](https://docs.gradle.org/current/userguide/build_environment.html#sec:accessing_the_web_via_a_proxy), the Gradle wrapper should download fine inside the Docker container as we mount the host's `HOME` directory. @heliocastro, can you confirm that this works as an alternative to passing the Java system properties on the command line via `-Dhttp.proxyUser` etc.?

**Comment by sschuberth** [comment]
The issue should have been fixed as far it is fixable: As Yarn respects the `http(s)_proxy` environment variables and these are now passed along to the Docker container, no separate proxy configuration for Yarn should be needed anymore. For Gradle, though, you still need to configure the proxy as documented [here](https://docs.gradle.org/current/userguide/build_environment.html#sec:accessing_the_web_via_a_proxy).
