### ISSUE TITLE
ort.tar not found

### ISSUE THREAD

**Issue by flixx** [heremaps/oss-review-toolkit#1637]
When executing `docker/run.sh [...]`, I get:

```
ADD failed: stat /var/lib/docker/tmp/docker-builder277680501/ort.tar: no such file or directory
```

In the [Dockerfile](https://github.com/heremaps/oss-review-toolkit/blob/master/docker/run/Dockerfile#L86) I see:
```
ADD ort.tar .
```

However, I don't know how to get the ort.tar. It is not in the source and not described in the documentation.

@sschuberth FYI since you recently added the Dockerfile.

Am I missing something?

Felix

**Comment by sschuberth** [comment]
I believe @bryan-woods recently had the same issue, which he's also [trying to circumvent as part of his Conda PR](https://github.com/heremaps/oss-review-toolkit/pull/1593/files#diff-5a7960fa2813ee1433c925dd1c59967dR101). However, I now had some time to look at the issue and believe to have found a solution. I'll propose a PR soon.
