### ISSUE TITLE
Using the oss-review-toolkit in IOS Projects

### ISSUE THREAD

**Issue by CleanHit** [heremaps/oss-review-toolkit#1930]
Can this tool be used with an IOS project or do I need to find a different OSS tool for that?

**Comment by sschuberth** [comment]
Neither [CocoaPods](https://github.com/heremaps/oss-review-toolkit/issues/87) nor [Swift](https://github.com/heremaps/oss-review-toolkit/issues/723) projects are *currently* supported. However, I heard that @tsteenbe might be starting to work on Swift support soon. What technology exactly would you require? (Please up-vote the respective existing issue so we can prioritize them accordingly.)

As an alternative to finding a different tool (*if* there is one), we're happily accepting pull requests to extend the analyzer's capabilities.

**Comment by CleanHit** [comment]
The project uses both CocoaPods and Swift packages, so it would be nice to have them both. I didn't find any windows or Linux based tools that can run an analysis outside of the Apple ecosystem. I've only found some IOS tools.

**Comment by sschuberth** [comment]
Ok, so would you be fine with closing this issue in favor of upvoting / subscribing to the respective two issues linked above?

**Comment by CleanHit** [comment]
Yes, thank you!
