### ISSUE TITLE
ORT seems to request an invalid composer version

### ISSUE THREAD

**Issue by friggingee** [heremaps/oss-review-toolkit#1941]
Clean repository clone, running `docker/build.sh` and `docker/run.sh` afterwards results in an error while running ORT on a project: "E: Version '1.9.0-2' for 'composer' was not found"

The version number is hardcoded in `docker/run/Dockerfile` and a quick search in the debian package repo seems to indicate that that version is not available anymore: https://packages.debian.org/search?suite=default&section=all&arch=any&searchon=names&keywords=composer

Can composer simply be updated to 1.9.1-1?

**Comment by sschuberth** [comment]
> Can composer simply be updated to 1.9.1-1?

Yes, a fix for this is already [underway](https://github.com/heremaps/oss-review-toolkit/pull/1933), we're just currently having Travis CI issues.

**Comment by sschuberth** [comment]
The fix was merged to `master`.
