### ISSUE TITLE
Process Chain to Create a Report of Used Licenses

### ISSUE THREAD

**Issue by CleanHit** [heremaps/oss-review-toolkit#1959]
Are those steps correct for creating a report of used licenses in a project. **Analyzer** --> **Scanner** --> **Reporter**. Does the final report include the whole license or only its name?

**Comment by sschuberth** [comment]
> Does the final report include the whole license or only its name?

That depends on the chosen report output format. E.g. the NOTICE report contains the license text (with the [limitation](https://github.com/heremaps/oss-review-toolkit/issues/1788#issuecomment-531132763) that text are "normalized" currently), but other reports like the Static HTML report only contain the license names / SPDX IDs, not the full texts.

But in general these are the steps, correct.

**Comment by CleanHit** [comment]
Thank you!
