### ISSUE TITLE
Consider using a "purl" as the package identifier

### ISSUE THREAD

**Issue by sschuberth** [heremaps/oss-review-toolkit#20]
Consider redesigning the package `identifier` as a "puurl" as described at https://github.com/nexB/scancode-toolkit/issues/805#issuecomment-340313273.

**Comment by sschuberth** [comment]
The "purl" (not anymore "puurl") specification has its own repository now: https://github.com/package-url/purl-spec

**Comment by pombredanne** [comment]
pinging myself to be kept posted on this ticket

**Comment by pombredanne** [comment]
For info @stevespringett contributed a Java implementation of Package URLs https://github.com/package-url/packageurl-java

**Comment by sschuberth** [comment]
> pinging myself to be kept posted on this ticket

Just click the "Subscribe" button on the right next time 😉

**Comment by sschuberth** [comment]
In https://github.com/heremaps/oss-review-toolkit/pull/1266 we stopped overriding `toString()` for `Identifier` in favor of introducing `toCoordinate()`. So there is no single "correct" string representation for an `Identifier` anymore, and https://github.com/heremaps/oss-review-toolkit/pull/1266/commits/68d8c3711a28fe84a7cfdcf29743be43e4af91e8 introduced `toPurl()` as *another* string representation that can be used at will.
