### ISSUE TITLE
REUSE badge from wrong source

### ISSUE THREAD

**Issue by mxmehl** [heremaps/oss-review-toolkit#2176]
The REUSE badge displayed on the README is pointing/sourced from the wrong repository, namely `fsfe/reuse-tool`.

To fix that, please register this project at https://api.reuse.software/register. After a few seconds, you'll be able to see the info page for this repo and be able to copy the Markdown code for this repo's REUSE status.

Thank you for being REUSE-compliant!

**Comment by tsteenbe** [comment]
@mxmehl  I tried to register ORT today but failed as ORT is already a registered project - believe @sschuberth did the registration so he likely the only one who can fix this issue. 

Or is there an alternative way to get the Markdown code? Would be great if https://api.reuse.software/register just return the MarkDown code for already registered projects.

**Comment by sschuberth** [comment]
See my PR, you just need to approve it @tsteenbe...

**Comment by mxmehl** [comment]
Thanks for the swift reaction! The PR looks good to me.

@tsteenbe Thanks for the enhancement request. I've opened an [issue in the project](https://git.fsfe.org/reuse/api/issues/35).
