### ISSUE TITLE
Could not download 'Gradle:package': DownloadException: Download failed for 'Gradle:package:1.0-SNAPSHOT

### ISSUE THREAD

**Issue by dineshr93** [heremaps/oss-review-toolkit#2194]
I was trying to run a scan command as mentioned below. its a maven dep project & has pom.xml file. but the I get download error. How to resolve this?

dinesh@dinesh-VirtualBox:~/ort/oss-review-toolkit/cli/build/install/ort/bin$ ./ort scan -i /home/dinesh/project/sdk-output/analyzer-result.yml -o /home/dinesh/project/sdk-output --scopes devDependencies
________ _____________________
\_____  \\______   \__    ___/ the OSS Review Toolkit, version 0.1.0-SNAPSHOT.
 /   |   \|       _/ |    |    Running 'scan' under Java 1.8.0_242 on Linux with
/    |    \    |   \ |    |    ORT_USER_HOME = /home/dinesh/.ort
\_______  /____|_  / |____|    SHELL = /bin/bash
        \/       \/
More environment variables:
TERM = xterm-256color

Using scanner 'ScanCode' with storage 'FileBasedStorage'.
11:51:40.609 [ScanCode-1] ERROR java.lang.Object - Could not download 'Gradle:com.example.appenginej8:helloworld:1.0-SNAPSHOT': DownloadException: Download failed for 'Gradle:com.example.appenginej8:helloworld:1.0-SNAPSHOT'.
Suppressed: DownloadException: No VCS URL provided for 'Gradle:com.example.appenginej8:helloworld:1.0-SNAPSHOT'. Please make sure the release POM file includes the SCM connection, see: https://docs.gradle.org/current/userguide/publishing_maven.html#example_customizing_the_pom_file, 
Suppressed: DownloadException: No source artifact URL provided for 'Gradle:com.example.appenginej8:helloworld:1.0-SNAPSHOT'.
Writing scan result to '/home/dinesh/project/sdk-output/scan-result.yml'.

**Comment by tsteenbe** [comment]
@dineshr93 To fix this DownloadException you need to ensure the pom.xml has a <scm> defining the source code repository. if it your Gradle package see https://docs.gradle.org/4.8/release-notes.html#customizing-the-generated-pom.

Note that if you get DownloadException for a dependency not created by you then as a workaround you can use curations see https://github.com/heremaps/oss-review-toolkit/blob/master/docs/config-file-curations-yml.md
