### ISSUE TITLE
Analyzer: exclude certain scopes already in Analyzer

### ISSUE THREAD

**Issue by kallesoranko** [heremaps/oss-review-toolkit#2216]
Are there any plans to implement something similar for Analyzer as there is `--scopes` for Scanner?

So what I would need is an `analyzer-result.yml` file with only certain scopes (compiled dependencies especially). This is because some people do not want to have test dependencies for example in `analyzer-result.yml` which is afterwards used with Antenna.

**Comment by sschuberth** [comment]
This somewhat goes against the philosophy of ORT that the analyzer always captures *all* data. The idea is that instead of leaving something out from the beginning, you rather "filter" the analyzer result in later steps. So to me, the correct place to implement something like this would not be in the analyzer, but in the component that sends the data to Antenna / SW360.

**Comment by kallesoranko** [comment]
We have two use cases for this:

1. User do  not want to have dev/test dependencies in SW360 -> **Filtering could be implemented in Antenna instead of ORT Analyzer** 

2. User wants to save `analyzer-result.yml` that is considered as SBoM to keep track about components and perform comparisons with SBoMs. This SBoM file shouldn't include dev/test dependencies.

**Comment by sschuberth** [comment]
Regarding 2., it's IMO not a good idea to directly use a custom file format like the analyzer result as an (S)BoM. The ORT analyzer / scan result files are meant to be interchange formats between technical tools in the compliance tool chain, but not as files that should be archived or distributed like a BoM. In ORT terms, the way to go would be to write a reporter that converts an analyzer / scan result to a BoM, or to extend one of the existing / upcoming reporters for CycloneDX or SPDX file formats.

**Comment by kallesoranko** [comment]
@sschuberth thanks for the comment and I also think that this is a good point. It is just really easy to compare two YML files with simple file comparison tools. I think that SPDX as it is today is just way too complex for this purpose but CycloneDX might fit here. Is it by the way possible to generate CycloneDX from `analyzer-result.yml` instead of `scan-result.yml`?  If no, why and would it be possible?

**Comment by sschuberth** [comment]
> I think that SPDX as it is today is just way too complex for this purpose but CycloneDX might fit here.

Note that the upcoming SPDX 3.0 spec will somewhat resolve this as it adds YAML as an output format among other things.

> Is it by the way possible to generate CycloneDX from `analyzer-result.yml` instead of `scan-result.yml`?

Yes, I just verified that's working: You can create a CycloneDX BOM from an `analyzer-result.yml` (i.e. an ORT result file with no scan results).

**Comment by kallesoranko** [comment]
I heard about this SPDX 3.0 in last oss-tooling-group meeting in Brussels and it did sound good. I am just assuming that it will take some time until it is available in ORT. 

That is really good news that CycloneDX reporter can use `analyzer-result.yml` directly 🎉.

I would say that all my questions are answered and from my point of view this issue can be closed.

**Comment by sschuberth** [comment]
> I am just assuming that it will take some time until it is available in ORT.

Actually, I guess it will take some time until the *spec* is ready, but once it is, ORT will be one of the first tools to support SPDX 3.0 :wink:

> I would say that all my questions are answered and from my point of view this issue can be closed.

Great, thank for the feedback!
