### ISSUE TITLE
Scanner failing to download dependencies with Analyzer Ort Results file?  

### ISSUE THREAD

**Issue by kchang264** [heremaps/oss-review-toolkit#2224]
Hi I was trying to run Scanner using the Ort Results file generated from Analyzer. I'm using the Mime types git repo from the Getting Started Docs and I'm running ORT on IntelliJ

Here are the arguments I'm using: 
--info scan -i /path/to/mime/analyzer-result.yml -o /path/to/scanner/output/scanner

After a while the Scanner just hangs. It seems like it would stay that way forever. It seems like there's a problem downloading some dependencies? 

Here's the last few lines of the log: 

>11:02:12.870 [main] INFO  kotlinx.coroutines.CoroutineScope - Using stored scan result(s) for NPM::mime-db:1.33.0 (120/209).

>11:02:12.928 [ScanCode-1] INFO  com.here.ort.downloader.Downloader - Detected VCS type 'Git' from type name 'Git'.
>11:02:12.931 [ScanCode-1] INFO  com.here.ort.utils.ProcessCapture - Running 'git --version' in ...
>11:02:12.932 [ScanCode-1] INFO  com.here.ort.downloader.VersionControlSystem - Using Git version 2.17.1.
>11:02:12.933 [ScanCode-1] INFO  com.here.ort.utils.ProcessCapture - Running 'git init' in...
>11:02:12.941 [ScanCode-1] INFO  com.here.ort.utils.ProcessCapture - Running 'git remote add origin ssh://git@github.com/isaacs/abbrev-js.git' in ...
>11:02:12.943 [ScanCode-1] INFO  com.here.ort.utils.ProcessCapture - Running 'git --version' in ...
>11:02:12.948 [ScanCode-1] INFO  com.here.ort.utils.ProcessCapture - Running 'git status -sb --porcelain=v2' in...
>11:02:12.951 [ScanCode-1] INFO  com.here.ort.utils.ProcessCapture - Running 'git remote show -n' in ...
>11:02:12.953 [ScanCode-1] INFO  com.here.ort.utils.ProcessCapture - Running 'git -c credential.helper= -c core.askpass=echo ls-remote --refs origin refs/heads/*' in ...

After I force terminate the process, I get these additional log lines: 
>11:16:01.440 [ScanCode-1] INFO  com.here.ort.downloader.VersionControlSystem - Meta-data has invalid Git revision 'c386cd9dbb1d8d7581718c54d4ba944cc9298d6f': IOException: Running 'git -c credential.helper= -c core.askpass=echo ls-remote --refs origin refs/heads/*' in ...  failed with exit code 130:
>
>11:16:01.448 [ScanCode-1] INFO  com.here.ort.utils.ProcessCapture - Running 'git status -sb --porcelain=v2' in '...
>
>Process finished with exit code 130 (interrupted by signal 2: SIGINT)
 

If anyone could give some insight as to what could be causing this it would be much appreciated.
Thanks.

**Comment by sschuberth** [comment]
The fact that I see the Git CLI being called (`git ls-remote`) tells me you're using a version that's several weeks old. Would you mind trying with the latest version from `master`?

**Comment by kchang264** [comment]
I tried it again with the latest version and I don't have the problem anymore. Thanks for the help!
