### ISSUE TITLE
A Question about the Scanner Scope Flag

### ISSUE THREAD

**Issue by CleanHit** [heremaps/oss-review-toolkit#2276]
If I'm scanning a Gradle based project then if I understood it correctly I can limit the examined [Gradle configurations](http://andresalmiray.com/maven-scopes-vs-gradle-configurations/) by specifying the one I want with the `--scopes `flag. Does it also mean that I can specify a flavoured configuration with this flag if my project uses different flavours?

**Comment by sschuberth** [comment]
Please note that the `--scopes` option for the scanner has been very recently replaced with a new `--skip-excluded` option, see #2271, and also the related discussion at https://github.com/heremaps/oss-review-toolkit/issues/2226.

So you should now use ScopeExcludes to exclude any unwanted scopes, and use the scanner's `--skip-excluded` option to also not scan any packages coming from those excluded scopes.

**Comment by CleanHit** [comment]
> Please note that the `--scopes` option for the scanner has been very recently replaced with a new `--skip-excluded` option, see #2271, and also the related discussion at #2226.
> 
> So you should now use ScopeExcludes to exclude any unwanted scopes, and use the scanner's `--skip-excluded` option to also not scan any packages coming from those excluded scopes.

It will be a very long list of excluded scopes (> 30), especially if the Gradle project uses different flavours. Is there a way to provide a (yaml) file with the excluded scopes with the `--skip-excluded` flag?

**Comment by sschuberth** [comment]
Scope excludes support regular expressions (also see my linked examples), so that should make it very easy to cover the wanted configurations with a few patterns only.

**Comment by CleanHit** [comment]
> Scope excludes support regular expressions (also see my linked examples), so that should make it very easy to cover the wanted configurations with a few patterns only.

So I can use this `--skip-excluded ^(?!.*\bcurrentProdReleaseRuntimeClasspath\b).*$` if I want to exclude everything but `currentProdReleaseRuntimeClasspath`, right?

**Comment by sschuberth** [comment]
Nope, `--skip-excluded` is a CLI option that takes no arguments. You first need to create an `.ort.yml` file [with excludes](https://github.com/heremaps/oss-review-toolkit/blob/master/docs/config-file-ort-yml.md#excludes), and then `--skip-excluded` tells the scanner to not scan excluded packages.

**Comment by CleanHit** [comment]
Ok so in my case that would be **my_exclude.ort.yml** file with: 
```yaml
excludes:
  scopes:
  - pattern: "^(?!.*\bcurrentProdReleaseRuntimeClasspath\b).*$"
    reason: "NOT_PRODUCTION"
    comment: "Exclude all scopes except of currentProdReleaseRuntimeClasspath."
```
And I'll have to loaded it with `--skip-excluded my_exclude.ort.yml`, correct? 
Do I need to specify the `reason` and `comment` keys or can I leave those out?

**Comment by sschuberth** [comment]
> And I'll have to load it with `--skip-excluded my_exclude.ort.yml`, correct?

No, still `--skip-excluded` is a CLI option that takes no arguments. If you want to use a different name than the default of `.ort.yml`, you need to use the analyzer's `--repository-configuration-file` option. The scanner will then automatically pick up the excludes from the analyzer result if the `--skip-excluded` option is passed to it.

> Do I need to specify the `reason` and `comment` keys or can I leave those out?

`comment` may be empty, but `reason` has to be one of [these reasons](https://github.com/heremaps/oss-review-toolkit/blob/21a5730f15bfc178fba327b0eac049cd81f23752/model/src/main/kotlin/config/ScopeExcludeReason.kt).

**Comment by CleanHit** [comment]
> > And I'll have to load it with `--skip-excluded my_exclude.ort.yml`, correct?
> 
> No, still `--skip-excluded` is a CLI option that takes no arguments. If you want to use a different name than the default of `.ort.yml`, you need to use the analyzer's `--repository-configuration-file` option. The scanner will then automatically pick up the excludes from the analyzer result if the `--skip-excluded` option is passed to it.
> 
> > Do I need to specify the `reason` and `comment` keys or can I leave those out?
> 
> `comment` may be empty, but `reason` has to be one of [these reasons](https://github.com/heremaps/oss-review-toolkit/blob/21a5730f15bfc178fba327b0eac049cd81f23752/model/src/main/kotlin/config/ScopeExcludeReason.kt).

This is a bit confusing, so lets see if I'm in the right detection. If I'm using a Gradle project I need too create a **gradle.ort.yml** file as described in the file examples [here](https://github.com/heremaps/oss-review-toolkit/blob/master/docs/config-file-ort-yml.md#excluding-scopes). I can change the `pattern:` key to `pattern: "^(?!.*\bcurrentProdReleaseRuntimeClasspath\b).*$"`.

If I'm correct so far with the creation of the **gradle.ort.yml** exclude file, do I put it in the same folder where my **analyzer-result.yml** lies so the `--skip-excluded` can find it or somewhere else?

**Comment by CleanHit** [comment]
I've created both **gradle-android.ort.yml** and **gradle.ort.yml** files with my values and put the in the same folder with my **analyzer-result.yml** file. After executing the needed `ort --info --debug scan ...` command with the new `--skip-exclude` flag I sometimes see this kind of information for different packages:
```bash
Running '/tmp/ort2565242544923732559ScanCode-3.0.2/scancode-toolkit-3.0.2/scancode --copyright --license --ignore *.ort.yml --info --strip-root --timeout 300 --ignore HERE_NOTICE --ignore META-INF/DEPENDENCIES --processes 7 --license-diag --verbose <my_path>/OSS_Project/here-oss/scan/v3/downloads/Maven/androidx.media/media/1.0.0 --json-pp <my_path>/OSS_Project/here-oss/scan/v3/native-scan-results/Maven/androidx.media/media/1.0.0/scan-results_ScanCode.json' in '<my_path>/OSS_Project/project_dir'...
```
Is it OK that it says `--ignore *.ort.yml`? I don't see at any point of the execution that it is using the information from my **gradle-android.ort.yml** and / or **gradle.ort.yml** files.

**Comment by sschuberth** [comment]
> Is it OK that it says `--ignore *.ort.yml`?

Yes. That's the command line to run the configured scanner with, and the scanner should not scan ORT's configuration file.

> I don't see at any point of the execution that it is using the information from my **gradle-android.ort.yml** and / or **gradle.ort.yml** files.

Please have a look at the generated ORT result file, i.e. `analyzer-results.yml`. If excludes from an ORT configuration file were picked up correctly, the ORT result file should contain an `excludes:` section  like [here](https://github.com/heremaps/oss-review-toolkit/blob/637fb02513c189f873f33efe57b929dbd0922159/analyzer/src/funTest/assets/projects/synthetic/gradle-all-dependencies-expected-result.yml#L14).

**Comment by CleanHit** [comment]
> Please have a look at the generated ORT result file, i.e. `analyzer-results.yml`. If excludes from an ORT configuration file were picked up correctly, the ORT result file should contain an `excludes:` section like [here](https://github.com/heremaps/oss-review-toolkit/blob/637fb02513c189f873f33efe57b929dbd0922159/analyzer/src/funTest/assets/projects/synthetic/gradle-all-dependencies-expected-result.yml#L14).

@sschuberth I guess that you mean the `scan-results.yml` file since I use the `--skip-excluded` with the `scan` command.

When I execute ` grep -B 2 -A 3 --color "excludes:" ./scan-result.yml` I don't get anything.

**Comment by sschuberth** [comment]
> I guess that you mean the `scan-results.yml` file since I use the `--skip-excluded` with the `scan` command.

No, I really meant `analyzer-results.yml`. The analyzer "bakes" the configured excludes from ORT configuration files (by default, `.ort.yml`) into the analyzer result. The scanner then takes `analyzer-results.yml` as input and produces `scan-results.yml` as output, i.e. the scanner has to know about the excludes *before* `scan-results.yml` is created.

The general idea with ORT result files (i.e. `analyzer-results.yml`, `scan-results.yml` etc.) is that output files always contain all of the input plus the data that the current tool produces. That is, `scan-results.yml` is essentially a copy of `analyzer-results.yml` plus scan results added, so that if you'd want to pass someone all of your results, you only need to pass `scan-results.yml`, not `analyzer-results.yml`.

**Comment by CleanHit** [comment]
@sschuberth So I've been placing my `gradle-android.ort.yml` and / or `gradle.ort.yml` files in the wrong place because the `analyze` command never picked them up. Running `grep -B 2 -A 3 --color "excludes:" ./analyzer-result.yml` didn't return any results.

I need the following infos:

1. Where do I put my modified `gradle-android.ort.yml` and / or `gradle.ort.yml` files for the analyzer to use them? In same folder, where my project `build.gradle` lies?
2. > The analyzer "bakes" the configured excludes from ORT configuration files (by default, `.ort.yml`) into the analyzer result.
Do you mean that it uses the information in `gradle-android.ort.yml` and / or `gradle.ort.yml` files by default without setting any additional flag with the `analyze` command?

**Comment by sschuberth** [comment]
> So I've been placing my `gradle-android.ort.yml` and / or `gradle.ort.yml` files in the wrong place

BTW, I'm still confused why you have *two* ORT configuarion files. ORT will only use *one* (project / repository specific) file at a time.

>     1. Where do I put my modified `gradle-android.ort.yml` and / or `gradle.ort.yml` files for the analyzer to use them?

Into the directory that you pass as the input to the analyzer via the `-i` option. But the file *has* to be called `.ort.yml`, unless you use the `--repository-configuration-file` to override this default location / name of the file.

>     2. Do you mean that it uses the information in `gradle-android.ort.yml` and / or `gradle.ort.yml` files by default without setting any additional flag with the `analyze` command?

Not quite, the file has to be called `.ort.yml` (see above). But then, yes, the file is used by default without the need to pass any additional command line options.

**Comment by CleanHit** [comment]
> BTW, I'm still confused why you have _two_ ORT configuarion files. ORT will only use _one_ (project / repository specific) file at a time.

You are right! I need only one file and now I see:
```bash
excludes:
      scopes:
      - pattern: "^(?!.*\bcurrentProdReleaseRuntimeClasspath\b).*$"
        reason: "BUILD_DEPENDENCY_OF"
        comment: "Packages for testing or development only."
```
In my `analyzer-results.yml` file. My only hope is that it understands my regular expression. I've tested it outside `ORT` and it works for 100%.

**Comment by sschuberth** [comment]
Correct!
