### ISSUE TITLE
Applied Filter menu for license value has no effect on package scan results table in scan-report-web-app.html

### ISSUE THREAD

**Issue by sgustafsson** [heremaps/oss-review-toolkit#2281]
In the generated file scan-report-web-app.html, when I apply the filter for one of the detected licenses in the "value" column, the package scan results table is not filtered by that license, the results table remains unchanged.

![image](https://user-images.githubusercontent.com/6702352/75518259-c8961400-5a00-11ea-9c03-61036589a560.png)

**Comment by tsteenbe** [comment]
@sgustafsson  Aware of this bug - have already fixed it in upcoming rewrite of the Reporter (eta < 2 weeks)

**Comment by tsteenbe** [comment]
@sgustafsson  [Major rewrite of the WebApp](https://github.com/heremaps/oss-review-toolkit/commit/4c6836e5ff0cb3dfeba992a099391dc33fbad720) has merged that fixes this issue. Please update your local copy of ORT.
