### ISSUE TITLE
OpenJDK 10 PKIX Error for Detekt Gradle Plugin 1.6

### ISSUE THREAD

**Issue by CleanHit** [heremaps/oss-review-toolkit#2284]
The latest master gives me this error under OpenJDK 10.0.2 but not under 12.0.2 when I execute `./gradlew installDist`:

```bash
[root@localhost oss-review-toolkit]# ./gradlew installDist
Configuration on demand is an incubating feature.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'oss-review-toolkit'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve io.gitlab.arturbosch.detekt:detekt-gradle-plugin:1.6.0.
     Required by:
         project : > io.gitlab.arturbosch.detekt:io.gitlab.arturbosch.detekt.gradle.plugin:1.6.0
      > Could not resolve io.gitlab.arturbosch.detekt:detekt-gradle-plugin:1.6.0.
         > Could not get resource 'https://plugins.gradle.org/m2/io/gitlab/arturbosch/detekt/detekt-gradle-plugin/1.6.0/detekt-gradle-plugin-1.6.0.module'.
            > Could not GET 'https://repo.jfrog.org/artifactory/libs-release-bintray/io/gitlab/arturbosch/detekt/detekt-gradle-plugin/1.6.0/detekt-gradle-plugin-1.6.0.module?referrer'.
               > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```
I guess I need to import an additional certificate again as described in issue [#2274 ](https://github.com/heremaps/oss-review-toolkit/issues/2274#issuecomment-591948242) because of the OpenJDK 10.X.X valid certifications problem. But generally speaking maybe the `ORT` should be suggested to use with OpenJDK 12.X.X (or 11.X.X if it works).

**Comment by sschuberth** [comment]
> I guess I need to import an additional certificate again as described in issue [#2274 ](https://github.com/heremaps/oss-review-toolkit/issues/2274#issuecomment-591948242) because of the OpenJDK 10.X.X valid certifications problem.

Exactly.

> But generally speaking maybe the `ORT` should be suggested to use with OpenJDK 12.X.X (or 11.X.X if it works).

Well, the interesting thing is that we don't see any such issues in our [OpenJDK 10 build on Travis CI](https://github.com/heremaps/oss-review-toolkit/blob/637fb02513c189f873f33efe57b929dbd0922159/.travis.yml#L7-L8), so my *guess* is that this is an issue with your specific *build* of OpenJDK 10 (there are quite significant differences between different builds of the same JDK version).

**Comment by CleanHit** [comment]
> Well, the interesting thing is that we don't see any such issues in our [OpenJDK 10 build on Travis CI](https://github.com/heremaps/oss-review-toolkit/blob/637fb02513c189f873f33efe57b929dbd0922159/.travis.yml#L7-L8), so my _guess_ is that this is an issue with your specific _build_ of OpenJDK 10 (there are quite significant differences between different builds of the same JDK version).

Ok I'm using the manually downloaded version form the official [distributor](https://jdk.java.net/archive/). I guess that something is word with their provided `cacerts` database, I'll be staying with OpenJDK 12.0.2 from now on :-).
