### ISSUE TITLE
NoticeByPackageReporter and NoticeSummaryReporter Files are Empty

### ISSUE THREAD

**Issue by CleanHit** [heremaps/oss-review-toolkit#2290]
The `NoticeByPackage` and `NOTICE_SUMMARY` files shows:
```txt
----

This project neither contains or depends on any third-party software components.
```
When executing `ort report` using the `evaluation-result.yml` file and:
```txt
Custom Header for Licenses and Copyright Notices:
================================================================================

----


----

This project contains no external packages, but may depend on such packages.

----

Notices generated with OSS Review Toolkit on Feb 28, 2020.
```
When executing `ort report` using the `scan-result.yml` file. In both cases the Static Html `scan-report.html` file lists libraries that have MIT and Apache 2.0 licenses.

**Comment by CleanHit** [comment]
I think it had a relation to issue #2292 . Because as soon as the regex got recognised by the `Analyzer` the `Scanner` (with `--skip-excluded`) could download the packages, after that `NoticeByPackageReporter` and `NoticeSummaryReporter` had the relevant information in them.

**Comment by sschuberth** [comment]
So, good to close this?

**Comment by CleanHit** [comment]
> So, good to close this?

Yes.
