### ISSUE TITLE
Questions about analyzer.

### ISSUE THREAD

**Issue by dd-lge** [heremaps/oss-review-toolkit#2295]
Hi, I have questions about analyzer.

Can I run the analyzer with only the scope that I want to analyze?
For example, I want to run the analyze the dependencies scope only (except devDependencies) in npm.
I couldn't find it in any documents.

Please help me!
Thank you.

**Comment by sschuberth** [comment]
> Can I run the analyzer with only the scope that I want to analyze?

Actually, no. That's not how the *Analyzer* is support to work, and coincidentally I just tried to clarify this as part of [this PR](https://github.com/heremaps/oss-review-toolkit/pull/2294/files#r386239771):

    The analyzer is supposed to capture *all* known information about a project, which can then be "filtered" in later steps.

**Comment by dd-lge** [comment]
@sschuberth 
The updated docs will be enough to answer this question.
Thank you for quick reply!
