### ISSUE TITLE
Downloader doesn't work with '--allow-moving-revisions' option.

### ISSUE THREAD

**Issue by dd-lge** [heremaps/oss-review-toolkit#2296]
Hi, I have a question about '--allow-moving-revisions' option in the downloader feature.

I tried to run the download module with the below command.
`./ort --info download -o /home/osc/download-test/ --allow-moving-revisions --project-url https://github.com/oracle/python-cx_Oracle`

 I expected that the downloader might download the 'master' git source code. But it returned the error like below.

```
17:32:26.061 [main] INFO  com.here.ort.downloader.Downloader - Trying to download source code for 'Downloader::python-cx_Oracle:'.
17:32:26.066 [main] INFO  com.here.ort.downloader.Downloader - Trying to download 'Downloader::python-cx_Oracle:' sources to '/home/osc/download-test/github2/Downloader/unknown/python-cx_Oracle/unknown' from VCS...
17:32:26.067 [main] INFO  com.here.ort.downloader.Downloader - Using processed VcsInfo(type=, url=https://github.com/oracle/python-cx_Oracle.git, revision=, resolvedRevision=null, path=). Original was VcsInfo(type=, url=https://github.com/oracle/python-cx_Oracle, revision=, resolvedRevision=null, path=).
17:32:27.358 [main] INFO  com.here.ort.downloader.Downloader - Detected VCS type 'Git' from URL 'https://github.com/oracle/python-cx_Oracle.git'.
17:32:27.364 [main] INFO  com.here.ort.utils.ProcessCapture - Running 'git --version' in '/home/osc/oss-review-toolkit/cli/build/install/ort/bin'...
17:32:27.366 [main] INFO  com.here.ort.downloader.VersionControlSystem - Using Git version 2.17.1.
17:32:27.451 [main] INFO  com.here.ort.utils.ProcessCapture - Running 'git --version' in '/home/osc/oss-review-toolkit/cli/build/install/ort/bin'...
17:32:28.223 [main] INFO  com.here.ort.downloader.VersionControlSystem - No Git revision for version '' found: IOException: No matching tag found for version ''. Please create a tag whose name contains the version.
17:32:28.229 [main] INFO  com.here.ort.downloader.Downloader - Trying to download source artifact for 'Downloader::python-cx_Oracle:' from ...
17:32:28.230 [main] ERROR com.here.ort.commands.DownloaderCommand - Could not download 'Downloader::python-cx_Oracle:': DownloadException: Download failed for 'Downloader::python-cx_Oracle:'.
Suppressed: DownloadException: Unable to determine a revision to checkout.,
Suppressed: DownloadException: No source artifact URL provided for 'Downloader::python-cx_Oracle:'.
17:32:28.230 [main] ERROR com.here.ort.commands.DownloaderCommand - Error Summary:

Could not download 'Downloader::python-cx_Oracle:': DownloadException: Download failed for 'Downloader::python-cx_Oracle:'.
Suppressed: DownloadException: Unable to determine a revision to checkout.,
Suppressed: DownloadException: No source artifact URL provided for 'Downloader::python-cx_Oracle:'.
Usage: ort download [OPTIONS]`
```

Did I run the wrong command? If not, it has an issue.
Please check this issue.

**Comment by sschuberth** [comment]
If you use `--project-url`, you also need to explicitly specify `--vcs-type`, `--vcs-revision` and eventually `--vcs-path` currently, as they all default to empty strings, and an empty string is not a valid revision.

However, I agree that *if* we can uniquely identify the VCS from the URL, we could come up with better defaults. I'll think about that.

**Comment by sschuberth** [comment]
As https://github.com/heremaps/oss-review-toolkit/pull/2298 was merged to provide smarter defaults, and the question was answered, I'm closing this. Feel free to reopen if you encounter any follow-up issues.

**Comment by dd-lge** [comment]
I tested the same command and it works well.( It downloaded the master source code of git repository.)
`./ort --info download -o /home/osc/download-test/ --allow-moving-revisions --project-url https://github.com/oracle/python-cx_Oracle`

But it works the same without '--allow-moving-revisions' option.
Depending on the usage of this option, it is unnecessary.

Please consider removing the '--allow-moving-revisions' option later.

**Comment by sschuberth** [comment]
> But it works the same without '--allow-moving-revisions' option.

For convenience of that use-case, `--allow-moving-revisions` is indeed [hard-coded](https://github.com/heremaps/oss-review-toolkit/blob/beb527b4e5156f0117b11688a6728fa1cde0496b/cli/src/main/kotlin/commands/DownloaderCommand.kt#L164) to `true` when using the Downloader with `--project-url`.

> Depending on the usage of this option, it is unnecessary.

The `--allow-moving-revisions` is still in use when using the Downloader with the `--ort-file` option (which should be the standard use-case).
