### ISSUE TITLE
local scancode scanner issue

### ISSUE THREAD

**Issue by dd-lge** [heremaps/oss-review-toolkit#2308]
My python version is 3.6.9. and I install the scancode toolkit with pip command.
`sudo -H pip install scancode-toolkit`
And the installed scancode-toolkit version is 3.1.1.

But it didn't use the local scanner. and download the scancode-toolkit v3.0.2.
```
16:55:44.630 [main] INFO  com.here.ort.scanner.LocalScanner - Bootstrapping scanner 'ScanCode' as required version 3.0.2 was not found in PATH.
16:55:44.631 [main] INFO  com.here.ort.scanner.scanners.ScanCode - Downloading ScanCode from https://github.com/nexB/scancode-toolkit/archive/v3.0.2.tar.gz...
```

But the scancode toolkit docs states that..
```
Note: If you use Python 2.7, scancode-toolkit Version 3.0.2 is installed by default. For Python 3 the latest version of
Scancode Toolkit is installed by default. Requesting a specific version through pip install for Python 3 will give
Errors if the Version isn’t 3.1.x or later.
```
and so the below command is not working in my python 3.6.9 environment .
`pip install scancode-toolkit`

How can I use the local scancode scanner based on python3?

**Comment by sschuberth** [comment]
ORT whitelists the versions of third-party tools it uses to ensure they work well with ORT. Currently, we expect ScanCode version 3.0.2 to be present. If it is not, it will be bootstrapped. However, ScanCode 3.0.2 does not support Python 3 yet. So if you want to use Python 3 and ScanCode 3.1.1, you need to change the source code in [this line](https://github.com/heremaps/oss-review-toolkit/blob/beb527b4e5156f0117b11688a6728fa1cde0496b/scanner/src/main/kotlin/scanners/ScanCode.kt#L216) to state `override val scannerVersion = "3.1.1"`.

**Comment by dd-lge** [comment]
I fixed and tested it.
The execution time for local scancode scanner took longer than for downloading scancode.
Do you know why?

**Comment by sschuberth** [comment]
Well, because ScanCode simply is not the faster scanner on earth :wink:

More seriously, obviously the scan time depends on the amount of code being scanned, whereas the download time should be more or less constant. So yes, if you scan a lot of code, that for sure takes much longer than downloading the ScanCode distribution.

**Comment by dd-lge** [comment]
It's just my mistake.
The first time I ran a local scancode scanner, the configuration time of local scancode is consumed.
However, this only works onece that I ran the command at first.
In conclusion, I checked that the local scancode scanner took less time. 
Thank you!
