### ISSUE TITLE
A Question about CycloneDX Scope Tag

### ISSUE THREAD

**Issue by CleanHit** [heremaps/oss-review-toolkit#2311]
Do all the excluded pattern scope packages have the
```xml
<scope>excluded</scope>
```
And the not excluded pattern scope the
```xml
<scope>required</scope>
```
Tag?

**Comment by sschuberth** [comment]
Yes, see [this code](https://github.com/heremaps/oss-review-toolkit/blob/cdedb42dfae9920b1c19e411f427e74486ad7833/reporter/src/main/kotlin/reporters/CycloneDxReporter.kt#L148). Cyclone DX only [offers](https://github.com/CycloneDX/cyclonedx-core-java/blob/b350b578240ce2ff7662213f8692ddc2d4f2fd6b/src/main/java/org/cyclonedx/model/Component.java#L49-L51) "required", "optional" and "excluded"; there is no "included".

**Comment by CleanHit** [comment]
> Yes, see [this code](https://github.com/heremaps/oss-review-toolkit/blob/cdedb42dfae9920b1c19e411f427e74486ad7833/reporter/src/main/kotlin/reporters/CycloneDxReporter.kt#L148). Cyclone DX only [offers](https://github.com/CycloneDX/cyclonedx-core-java/blob/b350b578240ce2ff7662213f8692ddc2d4f2fd6b/src/main/java/org/cyclonedx/model/Component.java#L49-L51) "required", "optional" and "excluded"; there is no "included".

What does "optional" scope mean? I thought that there are only "required" (aka included) and "excluded" scopes when using `ORT`

**Comment by CleanHit** [comment]
Are you using this exact [specification](https://cyclonedx.org/#specification-overview) or do you define additional specification fields as **"Required"**?

**Comment by sschuberth** [comment]
> What does "optional" scope mean?

That's something you need to ask the Cyclone DX guys, as it's them who specified that scope. We are not currently using it.

> Are you using this exact [specification](https://cyclonedx.org/#specification-overview) or do you define additional specification fields as **"Required"**?

ORT provides a super-set of the information that can be included in Cyclone DX. While we do not "define additional specification fields as required", we also populate any optional fields in Cyclone DX with information from ORT, and we ensure that the generated BOM [validates](https://github.com/heremaps/oss-review-toolkit/blob/cdedb42dfae9920b1c19e411f427e74486ad7833/reporter/src/funTest/kotlin/reporters/CycloneDxReporterTest.kt#L52) against the Cyclone DX specification.
