### ISSUE TITLE
Support tar.xz extension in Downloader module

### ISSUE THREAD

**Issue by dd-lge** [heremaps/oss-review-toolkit#2315]
I cannot download the tar file that has an extension of tar.xz.
(URL example : https://gstreamer.freedesktop.org/src/gst-plugins-base/gst-plugins-base-1.8.3.tar.xz)

Please support the more various type of file extensions for archive URL.

**Comment by sschuberth** [comment]
Strictly speaking, the issue should not be with *downloading* but with *unpacking*, but in any case I believe the issue should be fixed with https://github.com/heremaps/oss-review-toolkit/pull/2317.
