### ISSUE TITLE
scanner and postgres ssl configuration error

### ISSUE THREAD

**Issue by fb33** [heremaps/oss-review-toolkit#2322]
Hello,

I use ORT with Docker. I update this morning with the latest version of master and re-build a Docker image.
I use the Scanner with PostgreSQL Storage.
When I runned a scan and I've got this error:
```
14:50:45  Exception in thread "main" org.postgresql.util.PSQLException: The server does not support SSL.
14:50:45  	at org.postgresql.core.v3.ConnectionFactoryImpl.enableSSL(ConnectionFactoryImpl.java:435)
14:50:45  	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:139)
```
I readed the doc and I saw a new parameter for postgres configuration : `sslmode`
So I changed my config to add : `sslmode = "disabled"`
And now I've got this error : 
```
15:05:58  Exception in thread "main" org.postgresql.util.PSQLException: Invalid sslmode value: disabled
15:05:58  	at org.postgresql.jdbc.SslMode.of(SslMode.java:78)
15:05:58  	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:153)
```

I miss something ?

Regards

**Comment by fb33** [comment]
I find it !

There's a typo in the doc : 

> If you do not want to use SSL set the sslmode to disabled, other possible values are explained in the documentation. For other supported configuration options see PostgresStorageConfiguration.kt.

Should be `disable` and not `disabled`

**Comment by sschuberth** [comment]
Great finding @fb33! Will you be able to provide a PR?

@mnonnenmacher, can we introduce an `enum` for these values to avoid such issues in the future?

**Comment by mnonnenmacher** [comment]
> @mnonnenmacher, can we introduce an `enum` for these values to avoid such issues in the future?

I thougth about this but decided against it, because the JDBC driver will fail anyway if an invalid value is used, and the enum would not protect against typos in the docs or in the config file.
