### ISSUE TITLE
Analyzer Supported Managers

### ISSUE THREAD

**Issue by CleanHit** [heremaps/oss-review-toolkit#2343]
The `Analyzer` [source code](https://github.com/heremaps/oss-review-toolkit/tree/master/analyzer/src/main/kotlin/managers) shows support for `CocoaPods` but it is not listed under the `Analyzer` supported package managers in the [documentation](https://github.com/heremaps/oss-review-toolkit#details-on-the-tools).

From the documentation point of view there are no references to `Glide` and `dep` (only `Godep`) in the `Analyzer` [source code](https://github.com/heremaps/oss-review-toolkit/tree/master/analyzer/src/main/kotlin/managers).

Could you please clarify which package managers are currently supported by ORT?

**Comment by sschuberth** [comment]
CocaoPods is not (yet) supported, see [this code](https://github.com/heremaps/oss-review-toolkit/blob/bf142d4ec022fa1d4b3cc98c105640b6ed7ad9d2/analyzer/src/main/kotlin/managers/CocoaPods.kt#L50) and this [open issue](https://github.com/heremaps/oss-review-toolkit/issues/87).

[Glide](https://github.com/heremaps/oss-review-toolkit/blame/master/README.md#L190) and [dep](https://github.com/heremaps/oss-review-toolkit/blame/master/README.md#L187) support are listed as part of the `README.md`.

**Comment by CleanHit** [comment]
If the support for `CocoaPods` will be successful without the **macOS** requirement, will its implementation can be used in a similar way to support `Carthage` or is `Carthage` a whole different story?

**Comment by sschuberth** [comment]
Carthage support is a [separate issue](https://github.com/heremaps/oss-review-toolkit/issues/725).
