### ISSUE TITLE
Installation instructions and tests should be improved

### ISSUE THREAD

**Issue by jfinkhaeuser** [heremaps/oss-review-toolkit#398]
Here's what I did.

- Checked out the project: worked (duh)
- Ran `./gradlew sync`: worked
- Ran `./gradlew check`: failed
  - Some tests failed because external executables such as `hg` could not be found; *should* skip these tests.
  - Some tests failed because internal dependencies such as `/scanner/src/funTest/assets/scanners/scancode-toolkit/` could not be found; *should* just work.

Turns out that for that last issue, pulling git submodules gets one step further, so that should be added to the instructions.

But the test case still fails; the subsequent step that looks for `configure` in the same directory now works. I'm wondering why you're looking for `configure` if not to build binaries in that directory, and if so, why they're not built.

Lastly, `gradlew check` at some point just hangs, or seems to hang, with no indication what's going on. I killed it after about 15 minutes run-time.

At this point I'd abandon the project unless I had immediate need for it. I'm not sure how non-technical folk just interested in a compliance tool would react :)

**Comment by sschuberth** [comment]
Thanks for the report, we'll improve the `README.md`. While working on that, out of curiosity, what is `./gradlew sync` supposed to do? We do not define a `sync` task in our project, so it *should* fail, and so it does for me, but you say it worked for you?

**Comment by sschuberth** [comment]
`README.md` improvements are at https://github.com/heremaps/oss-review-toolkit/pull/400.

**Comment by sschuberth** [comment]
All linked improvements from my previous comment have been merged. If you encounter more hurdles, please file them as new specific issues. Thanks!
