### ISSUE TITLE
PIP: Python 3 Support

### ISSUE THREAD

**Issue by haikoschol** [heremaps/oss-review-toolkit#690]
The current Python/pip implementation does not try to determine which Python version to use for the project being analyzed and instead always uses Python 2.7.

There are ways to specify supported Python versions in both [setup.py](https://github.com/pypa/sampleproject/blob/master/setup.py#L106) and [requirements.txt](https://github.com/pypa/pip/pull/2134) files (as well as tox.ini and other files commonly found in Python projects). The analyzer could use that information to decide which version of Python/pip to invoke for gathering information about dependencies.

**Comment by adambhere** [comment]
Here's advice on how to detect if Python 3 vs Python 2 is needed: https://stackoverflow.com/questions/40886456/how-to-detect-if-code-is-python-3-compatible. If this works, no manually maintained metadata is required – and such metadata might not be correct anyway. Instead, the required information could be determined automatically as and when required. This would also eliminate any waiting for a standard or a standard that is most widely adopted.

**Comment by sschuberth** [comment]
Implemented by https://github.com/heremaps/oss-review-toolkit/pull/1146.
