### ISSUE TITLE
Add Cargo (Rust) as supported package manager

### ISSUE THREAD

**Issue by tsteenbe** [heremaps/oss-review-toolkit#724]
Add support for the Cargo dependency manager to the analyzer module.

https://github.com/rust-lang/cargo
https://doc.rust-lang.org/cargo/

**Comment by tsteenbe** [comment]
For ORT to work we need 3 things:
- dependency tree including dependency name, version
- declared license for a package
- source code location of the package

For the dependency tree, found the following:
- https://github.com/rust-lang/cargo/issues/1211 => seems Cargo maintainers do not see a need to make this a built-in feature
- https://crates.rs/crates/cargo-show => `cargo show --dependencies --json time` includes declared license and source code repository
- https://github.com/sfackler/cargo-tree => prints tree but has less features than cargo-show

**Comment by tsteenbe** [comment]
Offtopic - when we want to add Rust security advisories we could look at https://crates.rs/crates/cargo-audit

**Comment by sschuberth** [comment]
Another tool that might be useful: https://github.com/Nemo157/cargo-lichking
