### ISSUE TITLE
Add Conan (C/C++) as supported package manager

### ISSUE THREAD

**Issue by tsteenbe** [heremaps/oss-review-toolkit#726]
Add support for the Conan dependency manager to the analyzer module.

https://conan.io/

**Comment by tsteenbe** [comment]
To implement Conan support in ORT, we need several things things:

1. ability to detect whether a project is using Conan

>If a project has either [conanfile.py](https://docs.conan.io/en/latest/reference/conanfile.html) or [conanfile.txt](https://docs.conan.io/en/latest/reference/conanfile_txt.html) then it likely a Conan-based project. Can use this files for [globsForDefinitionFiles](https://github.com/heremaps/oss-review-toolkit/blob/master/analyzer/src/main/kotlin/managers/CocoaPods.kt#L40)

2. declared license for a package

> See [license in conanfile.py](https://docs.conan.io/en/latest/reference/conanfile/attributes.html#license), likely [conan info](https://docs.conan.io/en/latest/reference/commands/consumer/info.html) can be used to export this file's attributes to JSON so they can be read into ORT similar to how it's done in https://github.com/heremaps/oss-review-toolkit/blob/master/analyzer/src/main/kotlin/managers/Npm.kt
3. source code location of the package (VCS location + revision, package source code/binary artifact)

> See [scm in conanfile.py](https://docs.conan.io/en/latest/reference/conanfile/attributes.html#scm), likely [conan info](https://docs.conan.io/en/latest/reference/commands/consumer/info.html) can be used to read this value into ORT (same as above 2)

4. dependency tree including package name, version

> [conan info](https://docs.conan.io/en/latest/reference/commands/consumer/info.html) has a ` -g GRAPH` option to produce a DOT or HTML file. 

5.  Example Conan project that can be used to test Conan support

Maybe use https://github.com/pocoproject/conan-poco? or https://github.com/conan-community/conan-openssl?

As scopes I propose we use [requires](https://docs.conan.io/en/latest/reference/conanfile/attributes.html#requires) for dependencies and build-requires](https://docs.conan.io/en/latest/devtools/build_requires.html#build-requires) for build dependencies


No plugin should be required/to be installed in order to analyze Conan based projects

**Comment by tsteenbe** [comment]
@kallesoranko Created https://github.com/heremaps/oss-review-toolkit/tree/conan as a starting point to implement Conan support.

**Comment by sschuberth** [comment]
Resolved by https://github.com/heremaps/oss-review-toolkit/pull/1883, thank you @kallesoranko and @benmarsden!
