### ISSUE TITLE
Add React WebApp report

### ISSUE THREAD

**Issue by tsteenbe** [heremaps/oss-review-toolkit#733]
Currently the Reporter library supports as output format a static HTML file and an Excel which both only provide a limited user experience.

Proposal: Create single HTML file WebApp containing all JS, CSS , etc. based on React that provides three views to the results as tabs:

1. Summary: summary of scan results including overview of errors table
2. List: overview of detected projects with for each project a list that can be filtered on scope, level, declared license, detected licenses and status
3. List: overview of detected projects with each project display as a dependency tree similar to command line tree output found in many build tools

**Comment by sschuberth** [comment]
This has been merged.
