### ISSUE TITLE
Implement a way for users to address/suppress errors

### ISSUE THREAD

**Issue by tsteenbe** [heremaps/oss-review-toolkit#735]
Implement Evaluator library to address / suppress errors by comparing the location of error against what is and is not distributed as specified by the user in an `.ort.yml` file (#731).

**Motivation**
No all errors are equal / make sense to ask to be fixed by the ORT user. For example take the case where an error occurs in the Ruby code of https://github.com/grpc/grpc and only GRPC C++ code is used as a dependency.

**Comment by sschuberth** [comment]
Error resolution has been implemented independently of the evaluator as part of https://github.com/heremaps/oss-review-toolkit/pull/951.
