### ISSUE TITLE
 Implement a way for users to OK/NOT OK OSS licenses

### ISSUE THREAD

**Issue by tsteenbe** [heremaps/oss-review-toolkit#737]
Expand Evaluator library to evaluates the scan results from Scanner as OK or NOT OK based on user specified approval / rejection ruleset.

**Comment by tsteenbe** [comment]
@sschuberth  started implementation of #737 see already merged PRs
- https://github.com/heremaps/oss-review-toolkit/pull/1000
- https://github.com/heremaps/oss-review-toolkit/pull/1006

**Comment by sschuberth** [comment]
This has been implemented (but not fully documented yet) via custom rules written in Kotlin script, see [no_gpl_declared.kts](https://github.com/heremaps/oss-review-toolkit/blob/f42f5b8c02899e8a55ad94fd900d475ab5c606ee/evaluator/src/main/resources/rules/no_gpl_declared.kts) for an example.
