### ISSUE TITLE
 Implement a way for users to OK/NOT OK OSS license compatibility 

### ISSUE THREAD

**Issue by tsteenbe** [heremaps/oss-review-toolkit#738]
Expand Evaluator library to evaluates the scan results from Scanner as OK or NOT OK based on user specified license compatibility ruleset.

**Comment by sschuberth** [comment]
This has been implemented (but not fully documented yet) via custom rules written in Kotlin script, see [no_gpl_declared.kts](https://github.com/heremaps/oss-review-toolkit/blob/f42f5b8c02899e8a55ad94fd900d475ab5c606ee/evaluator/src/main/resources/rules/no_gpl_declared.kts) for an example.
