### ISSUE TITLE
Add docs how to run ORT using its Docker Image

### ISSUE THREAD

**Issue by tsteenbe** [heremaps/oss-review-toolkit#739]
Installing ORT with needed tools requires quite some efforts which may turn of potential ORT users.  If we provide better docs on how to run ORT using its Docker Image more people are likely willing to give ORT a try.

See also https://github.com/heremaps/oss-review-toolkit-docker

**Comment by sschuberth** [comment]
The *oss-review-toolkit-docker* repository was deleted in favor of PR #1123, i.e. ORT can bow be run from a Docker image via

    $ ./gradlew cli:dockerBuildImage
    $ docker run ort requirements

This still needs proper documentation, though, so I'm leaving this issue open.

**Comment by sschuberth** [comment]
Done by @tsteenbe himself in https://github.com/heremaps/oss-review-toolkit/pull/1159.
