### ISSUE TITLE
Retrieve curation information from ClearlyDefined API

### ISSUE THREAD

**Issue by tsteenbe** [heremaps/oss-review-toolkit#740]
Extend Analyzer to retrieve curations from APIs of https://clearlydefined.io/ to fix OSS packages with broke metadata

**Comment by sschuberth** [comment]
This was actually implemented as part of https://github.com/heremaps/oss-review-toolkit/pull/1945: If the analyzer is run with `--clearly-defined-curations`, ClearlyDefined will be used as a fall-back curation provider after local file curation provider has been tried first.
