### ISSUE TITLE
scanner: Limit scans to specific dependency scopes

### ISSUE THREAD

**Issue by mnonnenmacher** [heremaps/oss-review-toolkit#90]
Add a parameter to the scanner module to select which scopes will be scanned.

**Comment by sschuberth** [comment]
To clarify: Dependencies of all scopes should still be detected. It's just the scanner (or actually the downloader) that needs to get an option to filter dependencies by given scopes to consider. Correct, @mnonnenmacher?

**Comment by mnonnenmacher** [comment]
Yes, that's the scope of this ticket. But it also makes sense to add an option to the analyzer to perform dependency resolution only for specific scopes, we could do this in another ticket.

**Comment by sschuberth** [comment]
> But it also makes sense to add an option to the analyzer to perform dependency resolution only for specific scopes

I'm not actually sure about hat. So far our premise was to capture reality as closely as possible with the analyzer, and not interpret the results just yet. Also, for many package managers there's probably no performance gain to limit querying dependencies to a subset of scopes. But let's discuss that outside of this issue.
