### ISSUE TITLE
make JSON available output format for reporter in addition to current HTML and Excel

### ISSUE THREAD

**Issue by annania** [heremaps/oss-review-toolkit#907]
A flat file format like JSON makes for easier automation and data manipulation. Would like to view results in JSON file.

**Comment by sschuberth** [comment]
The reporter basically just transforms an "ORT result file" from the scanner into another format. As the ORT result file already is JSON (or YAML), we did not see a need for the reporter to support JSON output. Could you elaborate the need?

**Comment by annania** [comment]
Ahh, I see. You answered it. The reporter is an extra data transform step. So for automation we can use the scan-record.yml or json. Thanks!
