### ISSUE TITLE
Declared licenses in results should present licenses with SPDX identifier

### ISSUE THREAD

**Issue by annania** [heremaps/oss-review-toolkit#908]
I ran ORT against some projects and see licenses represented with varying names. For example I see in the excel results file in the Declared Licenses column: 

The Apache Software License, Version 2.0
Apache 2
Apache 2.0
Apache License
Apache Version 2.0
The Apache License, Version 2.0

All of these should be SPDX identifier for license: Apache-2.0
see SPDX license list: https://spdx.org/licenses/

**Comment by sschuberth** [comment]
*Declared* licenses (in contrast to *detected* licenses) are taken as-is from the meta-data of the packages. So if a package maintainer has a typo there, we'll have it, too. The rationale behind this was to detect exactly these varying names, and eventually report them back to the maintainers to ask them to use SPDX IDs already upstream.

**Comment by sschuberth** [comment]
Thinking out aloud, we could probably add an option to normalize declared licenses similar to how https://github.com/librariesio/spdx does.

**Comment by annania** [comment]
The Detected Licenses column is completely blank where Declared licenses is completely filled in for all found artifacts/packages. So should Detected Licenses have the SPDX identifier?

**Comment by annania** [comment]
![image](https://user-images.githubusercontent.com/5623183/46170597-336f7880-c26c-11e8-8532-3d0f912bd1e6.png)

**Comment by annania** [comment]
Can you check if any of these have a license file? or where does ORT put the source for dependencies or get source for dependencies?

**Comment by sschuberth** [comment]
There should be detected licenses for sure e.g. in `slf4j-api-1.7.6`. Can it be that you fed the reporter with the analyzer results, not with the scanner results?

**Comment by sschuberth** [comment]
The original issue has been solved as part of #1131 / #1293, please use the new `declared_licenses_processed` field now.
