### ISSUE TITLE
analyzer: Add Godep support

### ISSUE THREAD

**Issue by mnonnenmacher** [heremaps/oss-review-toolkit#91]
Add support for Godep to the analyzer module.

https://github.com/tools/godep

**Comment by artemnikitin** [comment]
For Go it will be better to support https://github.com/golang/dep instead of Godep. In the future, it will be "the package manager" for Go. 
For now, the tool might scan either `vendor` folder inside the project or $GOPATH, depends on project setup.

**Comment by sschuberth** [comment]
@artemnikitin We gladly accept contributions 😉

**Comment by sschuberth** [comment]
Resolved by https://github.com/heremaps/oss-review-toolkit/pull/442.
